const essays = [

    // ===== CIVIL PROCEDURE =====
    {
        subject: "civil-procedure",
        subjectLabel: "Civil Procedure",
        title: "Personal Jurisdiction and Service of Process",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format (Issue, Rule, Analysis, Conclusion).",
        prompt: "Paula, a California resident, was injured when she purchased a blender manufactured by HomeGoods Inc., a company incorporated in Delaware with its principal place of business in Texas. HomeGoods sells its products through a website that ships nationwide, and California is its third-largest market. Paula sues HomeGoods in California federal court. HomeGoods moves to dismiss for lack of personal jurisdiction. Paula also attempts to serve HomeGoods by mailing the complaint to the company's Texas headquarters. Discuss whether the California federal court has personal jurisdiction over HomeGoods, and whether Paula's service of process was proper.",
        issues: "Minimum contacts test; purposeful availment; stream of commerce; general vs. specific jurisdiction; proper methods of service on a corporation under FRCP Rule 4.",
        sampleAnswer: "1. PERSONAL JURISDICTION: Issue — Does California have personal jurisdiction over HomeGoods? Rule — Due process requires minimum contacts with the forum state such that suit does not offend traditional notions of fair play and substantial justice (Int'l Shoe). Specific jurisdiction exists when claims arise from defendant's forum contacts. Analysis — HomeGoods sells nationwide via website, California is its third-largest market, showing purposeful availment. Paula's claim arises from California sales. Conclusion — Specific jurisdiction likely exists. 2. SERVICE OF PROCESS: Issue — Was mailing to headquarters proper? Rule — FRCP 4(h) requires serving a corporation by delivering to an officer, managing agent, or as state law allows. Analysis — Simple mail to headquarters without acknowledgment likely insufficient under federal rules. Conclusion — Service was likely improper; Paula should re-serve properly."
    },
    {
        subject: "civil-procedure",
        subjectLabel: "Civil Procedure",
        title: "Summary Judgment and Burden of Proof",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Dan sues his former employer, Acme Corp., for wrongful termination. After discovery, Acme moves for summary judgment, arguing that Dan has no evidence of discriminatory intent. Dan opposes the motion, pointing to (1) a comment made by his supervisor six months before his termination that 'we need younger energy around here,' and (2) the fact that he was replaced by someone 15 years younger. Acme argues these facts are insufficient as a matter of law. Discuss how the court should rule on the summary judgment motion and what standard applies.",
        issues: "FRCP Rule 56 summary judgment standard; viewing facts in light most favorable to non-moving party; direct vs. circumstantial evidence of discrimination; shifting burdens under McDonnell Douglas.",
        sampleAnswer: "1. SUMMARY JUDGMENT STANDARD: Rule — Under FRCP 56, summary judgment is proper when there is no genuine dispute of material fact and movant is entitled to judgment as a matter of law. Court views facts in light most favorable to non-moving party. 2. BURDEN SHIFTING: Once Acme shows no direct evidence, burden shifts to Dan to show genuine dispute. Analysis — The supervisor's 'younger energy' comment is circumstantial evidence of age bias. Replacement by someone 15 years younger supports inference of discrimination. Together these create a genuine dispute of material fact. Conclusion — Court should deny summary judgment. A reasonable jury could find discriminatory intent based on these facts."
    },
    {
        subject: "civil-procedure",
        subjectLabel: "Civil Procedure",
        title: "Subject Matter Jurisdiction and Removal",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Maria, a California citizen, slips and falls at a grocery store owned by FreshMart Inc., a corporation incorporated in California with its principal place of business in California. She sues in California state court seeking $200,000 in damages for negligence. FreshMart attempts to remove the case to federal court, arguing the amount in controversy exceeds $75,000. Discuss whether removal to federal court is proper.",
        issues: "28 USC 1441 removal jurisdiction; diversity jurisdiction requirements; complete diversity rule; forum defendant rule; amount in controversy.",
        sampleAnswer: "1. REMOVAL STANDARD: Rule — Under 28 USC 1441, a defendant may remove a case to federal court if the federal court would have had original jurisdiction. 2. DIVERSITY JURISDICTION: Rule — Requires complete diversity (no plaintiff and defendant from same state) and amount exceeding $75,000. Analysis — Maria is a California citizen. FreshMart is incorporated in California with principal place of business in California — therefore also a California citizen. Complete diversity is destroyed. 3. FORUM DEFENDANT RULE: Even if diversity existed, 28 USC 1441(b)(2) bars removal when any defendant is a citizen of the state where the action was filed. FreshMart is a California citizen being sued in California. Conclusion — Removal is improper on both grounds. The case must remain in California state court."
    },

    // ===== CONTRACTS =====
    {
        subject: "contracts",
        subjectLabel: "Contracts",
        title: "Formation, Consideration, and Breach",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "On Monday, Sarah emailed Tom: 'I will sell you my vintage guitar for $3,000. This offer is good until Friday.' On Wednesday, Sarah sold the guitar to someone else and emailed Tom: 'Sorry, guitar is sold.' On Thursday, Tom emailed back: 'I accept your offer — see you Friday.' Tom then drove two hours to Sarah's house on Friday and she refused to sell. Tom sues for breach of contract. Discuss whether a contract was formed and whether Sarah is liable.",
        issues: "Offer and acceptance; revocation of offers; mailbox rule; option contracts; breach of contract; reliance damages.",
        sampleAnswer: "1. OFFER: Sarah's Monday email was a valid offer — definite terms, communicated to Tom. 2. REVOCATION: Rule — An offeror may revoke any time before acceptance unless there is an option contract supported by consideration. Analysis — Sarah's promise to keep offer open until Friday was not supported by consideration, so no option contract existed. Her Wednesday email was a valid revocation. 3. ACCEPTANCE: Tom's Thursday acceptance came after the Wednesday revocation. You cannot accept a revoked offer. 4. MAILBOX RULE: Acceptance is effective when sent, but revocation is effective when received. Tom received revocation Wednesday — before his Thursday acceptance. Conclusion — No contract was formed. However, Tom may have a promissory estoppel claim for reliance damages (cost of the two-hour drive) if he reasonably relied on the offer."
    },
    {
        subject: "contracts",
        subjectLabel: "Contracts",
        title: "Statute of Frauds and Part Performance",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Dan orally agreed to sell his house to Paula for $500,000. Paula paid a $50,000 deposit, hired an architect to redesign the interior for $8,000, and quit her job in another city to move. Dan later refused to sell, claiming the oral contract was unenforceable under the Statute of Frauds. Paula sues for specific performance. Discuss whether the Statute of Frauds bars enforcement, and what remedies Paula may be entitled to.",
        issues: "Statute of Frauds for real property; part performance exception; detrimental reliance; promissory estoppel; specific performance vs. restitution.",
        sampleAnswer: "1. STATUTE OF FRAUDS: Rule — Contracts for the sale of real property must be in writing to be enforceable. The oral agreement here would normally be unenforceable. 2. PART PERFORMANCE EXCEPTION: Rule — In equity, part performance can remove a contract from the Statute of Frauds when the acts are unequivocally referable to the contract. Analysis — Paula paid $50,000 deposit, hired architect, and quit her job — all actions unequivocally referable to the land sale agreement. 3. PROMISSORY ESTOPPEL: Even without part performance, Paula detrimentally relied on the promise to her detriment. Conclusion — Statute of Frauds likely does not bar enforcement due to part performance. Paula may seek specific performance (court orders Dan to sell) or restitution of her $50,000 deposit and $8,000 architect fees."
    },
    {
        subject: "contracts",
        subjectLabel: "Contracts",
        title: "Anticipatory Repudiation and Damages",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "ABC Corp. contracted with XYZ Builders to construct a new office for $500,000, with completion due December 1. On October 1, XYZ told ABC: 'We cannot finish by December 1 and we are walking off the job.' ABC immediately hired another contractor who completed the work for $620,000. ABC sues XYZ for the $120,000 difference. XYZ argues ABC should have waited until December 1 to sue. Discuss ABC's rights and remedies.",
        issues: "Anticipatory repudiation; election of remedies; duty to mitigate; expectation damages; cost of completion.",
        sampleAnswer: "1. ANTICIPATORY REPUDIATION: Rule — When a party clearly and unequivocally repudiates a contract before performance is due, the non-breaching party may treat it as immediate breach and sue right away. Analysis — XYZ's October 1 statement was a clear repudiation — no need to wait until December 1. 2. DUTY TO MITIGATE: Rule — Non-breaching party must take reasonable steps to mitigate damages. Analysis — ABC acted reasonably by immediately hiring a replacement contractor. 3. DAMAGES: Rule — Expectation damages put plaintiff in position they would have been in had contract been performed. Analysis — ABC expected to pay $500,000 for a completed building. They paid $620,000. Conclusion — ABC is entitled to $120,000 — the difference between the contract price and the replacement cost. XYZ's argument that ABC had to wait until December 1 fails because anticipatory repudiation allows immediate suit."
    },

    // ===== TORTS =====
    {
        subject: "torts",
        subjectLabel: "Torts",
        title: "Negligence and Premises Liability",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Mike owns a hardware store. He recently had the floors waxed but did not put up any warning signs. A customer, Linda, entered the store, slipped on the freshly waxed floor, and broke her wrist. There is a security camera showing Mike inspecting the floor just 20 minutes before Linda's fall. Linda sues Mike for negligence. Mike argues Linda was also negligent because she was looking at her phone when she fell. Discuss Mike's liability and the effect of Linda's conduct.",
        issues: "Negligence elements; duty to business invitees; breach; actual and proximate cause; damages; comparative negligence in California; pure comparative fault.",
        sampleAnswer: "1. DUTY: Mike owed Linda, a business invitee, the highest duty of care — to inspect for and repair or warn of dangerous conditions. 2. BREACH: Mike knew of the freshly waxed floor (camera shows he inspected it) and failed to warn. This falls below the standard of a reasonable store owner. 3. CAUSATION: The wet floor was the actual cause (but-for) and proximate cause of Linda's fall and injury. 4. DAMAGES: Linda suffered a broken wrist — actual physical damages. 5. COMPARATIVE NEGLIGENCE: Rule — California follows pure comparative fault. A plaintiff's own negligence reduces but does not bar recovery. Analysis — If Linda was 20% at fault for looking at her phone, she recovers 80% of her damages. Conclusion — Mike is liable. Linda's phone use reduces but does not eliminate her recovery under California's pure comparative fault system."
    },
    {
        subject: "torts",
        subjectLabel: "Torts",
        title: "Products Liability",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "FastBlend manufactures a blender. The blender has a design defect — the lid can fly off during use at high speeds, but the manual does not warn of this risk. Carol buys the blender at a department store, uses it on high speed, the lid flies off, and hot soup burns her face. She sues FastBlend and the department store. Discuss the products liability claims available to Carol.",
        issues: "Strict products liability; manufacturing defect vs. design defect vs. failure to warn; liability of manufacturers and retailers; damages.",
        sampleAnswer: "1. STRICT PRODUCTS LIABILITY (Design Defect): Rule — A product has a design defect if the entire product line is defective and a reasonable alternative design existed. Analysis — The lid flying off on high speed affects all units. A locking lid mechanism was likely feasible. FastBlend is liable for design defect. 2. FAILURE TO WARN: Rule — Manufacturers must warn of non-obvious dangers. Analysis — The lid ejection risk is not obvious to consumers. The manual's silence is a failure to warn. This is an independent basis for liability. 3. RETAILER LIABILITY: Rule — Under strict liability, all commercial sellers in the distribution chain are liable. Analysis — The department store sold the defective product and is also strictly liable. 4. DAMAGES: Carol suffered physical injury (burns) — recoverable under strict liability. Conclusion — Carol has viable strict liability claims against both FastBlend (design defect and failure to warn) and the department store (as seller in distribution chain)."
    },
    {
        subject: "torts",
        subjectLabel: "Torts",
        title: "Defamation and Privacy",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "A local newspaper publishes an article stating that Dr. Jones, a well-known surgeon, 'botched three surgeries last year due to drinking on the job.' The statement is false. Dr. Jones sues for defamation. The newspaper argues it is protected by the First Amendment and that Dr. Jones must prove actual malice. Dr. Jones argues he is a private figure. Discuss the defamation claim and the applicable standard.",
        issues: "Defamation elements; public figure vs. private figure; actual malice standard; New York Times v. Sullivan; falsity; damages.",
        sampleAnswer: "1. DEFAMATION ELEMENTS: (1) Defamatory statement — accusing a doctor of drunk surgery is clearly defamatory; (2) Of and concerning plaintiff — names Dr. Jones specifically; (3) Publication — printed in newspaper; (4) Damages — harm to professional reputation. 2. PUBLIC VS. PRIVATE FIGURE: Rule — Public figures must prove actual malice (knowledge of falsity or reckless disregard for truth). Private figures need only prove negligence (in most states). Analysis — Dr. Jones is a local surgeon, not a celebrity or public official. A 'well-known' local professional is likely a private figure. 3. STANDARD: As a private figure, Dr. Jones need only prove the newspaper was negligent in publishing the false statement — a lower bar than actual malice. Conclusion — Dr. Jones has a strong defamation claim. The statement is false, defamatory, published, and Dr. Jones as a private figure need only show negligence, not actual malice."
    },

    // ===== CRIMINAL LAW =====
    {
        subject: "criminal",
        subjectLabel: "Criminal Law & Procedure",
        title: "Homicide and Defenses",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Dave comes home and finds his wife in bed with his neighbor, Bob. In a rage, Dave grabs a kitchen knife and stabs Bob, killing him. Dave is charged with first degree murder. At trial, Dave argues he acted in the heat of passion and should be convicted of voluntary manslaughter at most. The prosecution argues the killing was premeditated. Discuss what charges are appropriate and what defenses apply.",
        issues: "First degree murder; second degree murder; voluntary manslaughter; heat of passion; adequate provocation; premeditation and deliberation; cooling off period.",
        sampleAnswer: "1. FIRST DEGREE MURDER: Requires premeditation and deliberation — a calm, cool decision to kill. Analysis — Dave acted in immediate rage upon discovery. No evidence of prior planning. First degree murder is unlikely. 2. SECOND DEGREE MURDER: Requires malice aforethought without premeditation. Analysis — Grabbing a knife and stabbing shows intent to kill or cause serious harm — malice is present. Second degree murder is possible. 3. VOLUNTARY MANSLAUGHTER: Rule — Reduces murder to manslaughter when defendant acted in heat of passion upon adequate legal provocation, without cooling off time. Analysis — Finding a spouse in adultery is classic adequate provocation at common law. Dave acted immediately — no cooling off period. Conclusion — Dave should most likely be convicted of voluntary manslaughter, not first degree murder. The heat of passion defense negates the malice required for murder. However, if the jury finds Dave had time to cool off, second degree murder is possible."
    },
    {
        subject: "criminal",
        subjectLabel: "Criminal Law & Procedure",
        title: "Fourth Amendment Search and Seizure",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Officer Smith receives an anonymous tip that Dan is selling drugs from his apartment. Without obtaining a warrant, Officer Smith goes to Dan's apartment building, stands in the hallway, and uses a drug-sniffing dog which alerts to Dan's door. Officer Smith then kicks in the door and finds drugs inside. Dan moves to suppress the evidence. Discuss whether the search was constitutional.",
        issues: "Fourth Amendment; reasonable expectation of privacy; anonymous tips and probable cause; use of drug-sniffing dogs; warrantless entry; exigent circumstances; exclusionary rule.",
        sampleAnswer: "1. ANONYMOUS TIP: Rule — An anonymous tip alone is generally insufficient for probable cause without corroboration (Illinois v. Gates totality of circumstances). Analysis — Uncorroborated anonymous tip provides weak probable cause basis. 2. DRUG-SNIFFING DOG IN HALLWAY: Rule — Florida v. Jardines held that bringing a drug-sniffing dog onto a home's curtilage to gather evidence is a Fourth Amendment search requiring a warrant. Analysis — An apartment hallway may be curtilage depending on access. Dog sniff likely constitutes a search. 3. WARRANTLESS ENTRY: Rule — Warrantless home entry is presumptively unreasonable. Exigent circumstances (imminent destruction of evidence, hot pursuit) can justify entry. Analysis — No exigent circumstances shown — officer acted on a tip, not on observing imminent destruction. Conclusion — The search was unconstitutional. No valid warrant, no sufficient probable cause from anonymous tip alone, and warrantless entry lacked exigent circumstances. Evidence should be suppressed under the exclusionary rule."
    },
    {
        subject: "criminal",
        subjectLabel: "Criminal Law & Procedure",
        title: "Conspiracy and Accomplice Liability",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Ann and Bob agree to rob a bank. Carl, Ann's brother, drives them to the bank knowing their plan, but waits in the car. During the robbery, Bob shoots and kills a security guard — something Ann and Carl did not plan or expect. Discuss the criminal liability of Ann, Bob, and Carl.",
        issues: "Conspiracy; overt act requirement; accomplice liability; Pinkerton doctrine; felony murder; withdrawal from conspiracy.",
        sampleAnswer: "1. CONSPIRACY — ALL THREE: Ann and Bob agreed to rob the bank — conspiracy formed. Carl knowingly drove them — he joined the conspiracy through his assistance. All three are liable for conspiracy. 2. BANK ROBBERY — ANN AND CARL: As conspirators and accomplices, both are liable for the planned robbery. Carl aided by driving — accomplice liability attaches. 3. FELONY MURDER — BOB: Bob committed the killing during the robbery — first degree felony murder. 4. PINKERTON DOCTRINE — ANN AND CARL: Rule — Co-conspirators are liable for foreseeable crimes committed by co-conspirators in furtherance of the conspiracy. Analysis — A shooting during a bank robbery is foreseeable even if unplanned. Conclusion — Ann and Carl are likely liable for felony murder under Pinkerton. All three face serious criminal liability. Carl cannot escape by staying in the car — his knowing assistance makes him an accomplice."
    },

    // ===== EVIDENCE =====
    {
        subject: "evidence",
        subjectLabel: "Evidence",
        title: "Hearsay and Exceptions",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "In a personal injury trial, plaintiff's attorney seeks to introduce three pieces of evidence: (1) A statement the defendant made to a friend the day after the accident saying 'I ran the red light'; (2) A hospital record from the day of the accident noting the plaintiff 'complained of severe back pain'; (3) Testimony from a witness who heard the plaintiff shout 'Watch out, he's running the light!' just before the crash. Defendant objects to all three as hearsay. Discuss whether each item is admissible.",
        issues: "Hearsay definition; party admissions; business records exception; present sense impression; excited utterance; verbal acts; FRE 801-804.",
        sampleAnswer: "1. DEFENDANT'S STATEMENT TO FRIEND: Rule — Statements by a party opponent are excluded from hearsay under FRE 801(d)(2). Analysis — Defendant is a party; his admission that he ran the red light is a party admission. Conclusion — Admissible as non-hearsay party admission. 2. HOSPITAL RECORD: Rule — Business records are admissible under FRE 803(6) if made in the regular course of business, at or near the time of the event, by someone with knowledge. Analysis — Hospital records of patient complaints are routinely kept business records made contemporaneously. Conclusion — Admissible under the business records exception. 3. PLAINTIFF'S SHOUT: Rule — Present sense impression (FRE 803(1)) covers statements made while perceiving an event. Excited utterance (FRE 803(2)) covers statements made under stress of excitement. Analysis — The shout was made in the moment of perceiving the dangerous event, under obvious excitement. Conclusion — Admissible under both present sense impression and excited utterance exceptions."
    },
    {
        subject: "evidence",
        subjectLabel: "Evidence",
        title: "Witness Credibility and Impeachment",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "At trial, the key witness for the prosecution testifies that she saw the defendant commit the crime. On cross-examination, defense counsel wants to: (1) Ask about a prior felony conviction for fraud from 8 years ago; (2) Ask about a prior inconsistent statement she gave to police saying she was 'not sure' who she saw; (3) Introduce evidence that the witness has a close personal relationship with the victim's family. Discuss the admissibility of each impeachment method.",
        issues: "Impeachment methods; prior felony convictions FRE 609; prior inconsistent statements FRE 613; bias; FRE 403 balancing; credibility of witnesses.",
        sampleAnswer: "1. PRIOR FELONY CONVICTION: Rule — FRE 609 allows impeachment with prior felony convictions if probative value outweighs prejudicial effect (for non-defendant witnesses, standard is FRE 403). Convictions over 10 years old face higher bar. Analysis — Fraud conviction (8 years ago) relates to truthfulness — highly probative for credibility. Under 10 years. Likely admissible. 2. PRIOR INCONSISTENT STATEMENT: Rule — FRE 613 allows prior inconsistent statements to impeach. Witness must be given opportunity to explain. Analysis — Telling police she was 'not sure' directly contradicts her certain trial testimony. Admissible for impeachment (not for truth of matter). 3. BIAS THROUGH RELATIONSHIP: Rule — Bias is always a proper ground for impeachment and is not subject to FRE 608 limitations. Analysis — A close relationship with the victim's family suggests motive to favor prosecution. Conclusion — All three impeachment methods are admissible. The jury may then weigh the witness's credibility accordingly."
    },
    {
        subject: "evidence",
        subjectLabel: "Evidence",
        title: "Character Evidence and Prior Bad Acts",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Dan is on trial for assault. The prosecution wants to introduce evidence that: (1) Dan has a 'reputation in the community for being violent'; (2) Dan punched a coworker in a separate incident two years ago; (3) Dan told a friend 'I like to fight when I'm angry.' The defense objects to all three. Discuss the admissibility of each piece of evidence.",
        issues: "Character evidence FRE 404; propensity evidence prohibition; FRE 404(b) other acts; methods of proving character FRE 405; reputation vs. opinion vs. specific instances.",
        sampleAnswer: "1. COMMUNITY REPUTATION FOR VIOLENCE: Rule — FRE 404(a) prohibits character evidence to prove propensity (acting in conformity). In criminal cases, prosecution cannot introduce defendant's bad character first — must wait for defendant to open the door. Analysis — Prosecution offering this in its case-in-chief is improper propensity evidence. Conclusion — Inadmissible in prosecution's case-in-chief. 2. PRIOR PUNCH OF COWORKER: Rule — FRE 404(b) prohibits other acts to prove propensity but allows them for other purposes: motive, intent, plan, knowledge, absence of mistake. Analysis — Prosecution must show a non-propensity purpose. If offered just to show 'he's a violent person,' inadmissible. If offered to show intent or common scheme, may be admissible. Conclusion — Likely inadmissible without a specific non-propensity purpose. 3. DAN'S OWN STATEMENT: Rule — Statements by a party opponent are non-hearsay admissions under FRE 801(d)(2). Analysis — Dan's own words expressing his mindset are admissible as a party admission and as relevant to his state of mind. Conclusion — Admissible."
    },

    // ===== CONSTITUTIONAL LAW =====
    {
        subject: "constitutional",
        subjectLabel: "Constitutional Law",
        title: "Equal Protection and Suspect Classifications",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "A state passes a law requiring that all state government jobs requiring security clearance be held only by U.S. citizens, excluding lawful permanent residents (green card holders). Maria, a lawful permanent resident who was denied a state job, sues arguing the law violates the Equal Protection Clause. The state argues the law is necessary to protect sensitive government information. Discuss whether the law is constitutional.",
        issues: "Equal protection; alienage classification; strict scrutiny for alienage; political function exception; Fourteenth Amendment; compelling government interest.",
        sampleAnswer: "1. EQUAL PROTECTION FRAMEWORK: The Fourteenth Amendment prohibits states from denying equal protection. Courts apply different scrutiny levels based on the classification. 2. ALIENAGE CLASSIFICATION: Rule — State laws discriminating against lawful aliens are generally subject to strict scrutiny (Graham v. Richardson). The government must show a compelling interest and narrow tailoring. 3. POLITICAL FUNCTION EXCEPTION: Rule — Exception to strict scrutiny for laws excluding aliens from positions that go to the heart of representative government (e.g., teachers, police, probation officers). Analysis — Security clearance jobs may fall under the political function exception if they involve policymaking or law enforcement. If exception applies, rational basis review applies instead. 4. APPLICATION: If strict scrutiny applies — protecting sensitive information is compelling, but blanket exclusion of all permanent residents may not be narrowly tailored. Conclusion — Constitutionality depends on whether political function exception applies. If yes, likely constitutional. If no, likely unconstitutional under strict scrutiny."
    },
    {
        subject: "constitutional",
        subjectLabel: "Constitutional Law",
        title: "First Amendment Free Speech",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "A city ordinance prohibits all 'loud amplified sound' in public parks between 9am and 9pm. A political activist group wants to hold a rally using amplified speakers in a public park at 2pm on a Saturday. The city denies their permit. The group sues, arguing the ordinance violates their First Amendment rights. The city argues the ordinance is a reasonable time, place, and manner restriction. Discuss the constitutional issues.",
        issues: "First Amendment; public forum doctrine; content-neutral vs. content-based restrictions; time place and manner restrictions; prior restraint; intermediate scrutiny.",
        sampleAnswer: "1. PUBLIC FORUM: Public parks are traditional public forums — the government's ability to restrict speech is very limited. 2. CONTENT-NEUTRAL ANALYSIS: Rule — Content-neutral restrictions (not based on message) are valid if: (1) narrowly tailored, (2) serve a significant government interest, and (3) leave open alternative channels of communication. Analysis — The ordinance bans all loud amplified sound regardless of content — content-neutral. 3. SIGNIFICANT INTEREST: Reducing noise pollution in parks is a legitimate government interest. 4. NARROW TAILORING: The ordinance covers all hours from 9am-9pm — this is quite broad. A narrower restriction (e.g., early morning/late night only) might serve the same interest. 5. ALTERNATIVE CHANNELS: Can the group speak without amplification? This may be an inadequate alternative for a large rally. Conclusion — The ordinance may fail the narrow tailoring requirement. A complete daytime ban on amplified sound in public parks likely goes further than necessary and may not leave adequate alternative channels for effective political speech."
    },
    {
        subject: "constitutional",
        subjectLabel: "Constitutional Law",
        title: "Due Process and Fundamental Rights",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "A state law requires that any parent who has been convicted of a non-violent drug offense within the past 10 years must complete a government-approved parenting class before being allowed to have unsupervised visits with their children. A father convicted of marijuana possession 3 years ago challenges the law as violating his fundamental right to parent his children without interference. Discuss the constitutional issues.",
        issues: "Substantive due process; fundamental rights; parental rights; strict scrutiny; compelling government interest; narrow tailoring; Troxel v. Granville.",
        sampleAnswer: "1. SUBSTANTIVE DUE PROCESS: The Due Process Clause protects fundamental rights from government interference. 2. PARENTAL RIGHTS AS FUNDAMENTAL: Rule — The right to direct the upbringing of one's children is a fundamental liberty interest (Troxel v. Granville; Meyer v. Nebraska). Strict scrutiny applies to laws burdening fundamental rights. 3. STRICT SCRUTINY: Government must show: (1) compelling interest and (2) narrow tailoring. Analysis — Protecting children's welfare is a compelling interest. However, requiring parenting classes based solely on a past non-violent drug conviction, regardless of actual parenting fitness, may not be narrowly tailored. It creates an irrebuttable presumption that all such parents are unfit — no individualized assessment. 4. PROCEDURAL CONCERNS: No individualized hearing to assess actual parental fitness may also raise procedural due process concerns. Conclusion — The law likely fails strict scrutiny. While child welfare is compelling, the blanket requirement without individualized assessment is not narrowly tailored to that interest."
    },

    // ===== REAL PROPERTY =====
    {
        subject: "real-property",
        subjectLabel: "Real Property",
        title: "Adverse Possession",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "In 2010, Owen purchased a large lot. An old fence on the property was actually 10 feet over the property line onto the adjacent lot owned by Ned. Owen mowed the grass, planted a garden, and maintained this strip of land openly every year, believing it was his property. Ned lived out of state and never visited. In 2023, Ned returns and discovers Owen's use. California's adverse possession statute requires 5 years of possession plus payment of property taxes. Owen paid taxes only on his own recorded lot, not on Ned's strip. Discuss whether Owen has acquired title by adverse possession.",
        issues: "California adverse possession requirements; actual possession; open and notorious; hostile; exclusive; continuous; California tax payment requirement; color of title.",
        sampleAnswer: "1. ADVERSE POSSESSION ELEMENTS: (1) Actual Possession — Owen mowed and gardened the strip. Met. (2) Open and Notorious — Visible maintenance for 13 years. Met. (3) Hostile — Owen believed it was his (objective standard in most states). Met. (4) Exclusive — No evidence Ned used the strip. Met. (5) Continuous — Annual maintenance for 13 years. Met. 2. CALIFORNIA TAX REQUIREMENT: Rule — California requires the adverse possessor to have paid all taxes levied on the property for the statutory period (CCP § 325). Analysis — Owen paid taxes only on his own lot. He did NOT pay taxes on Ned's strip. This is fatal to the adverse possession claim in California. Conclusion — Owen fails to acquire title by adverse possession in California because he did not pay property taxes on the disputed strip. This is a critical California-specific rule. Owen may have claims in other jurisdictions without the tax requirement, but not in California."
    },
    {
        subject: "real-property",
        subjectLabel: "Real Property",
        title: "Landlord-Tenant and Habitability",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Tom rents an apartment from Landlord Larry under a one-year lease at $2,000 per month. After three months, Tom discovers the heating system is broken and there is toxic mold in the bathroom. Tom notifies Larry in writing. Larry does nothing for two months. Tom stops paying rent and moves out. Larry sues Tom for unpaid rent. Tom counterclaims for breach of the implied warranty of habitability. Discuss the rights and obligations of both parties.",
        issues: "Implied warranty of habitability; constructive eviction; rent withholding remedies; repair and deduct; retaliatory eviction; landlord's duty to repair; tenant's duty to pay rent.",
        sampleAnswer: "1. IMPLIED WARRANTY OF HABITABILITY: Rule — Landlords impliedly warrant that residential premises are fit for human habitation throughout the tenancy. Broken heat and toxic mold breach this warranty. 2. LARRY'S BREACH: Tom gave written notice — Larry had reasonable time to repair and failed to act for two months. Clear breach of habitability warranty. 3. TOM'S REMEDIES: (a) Rent withholding — Many states allow tenants to withhold rent when warranty is breached; (b) Repair and deduct — Tenant pays for repair and deducts from rent; (c) Constructive eviction — If conditions make unit uninhabitable and tenant vacates, landlord cannot collect rent. 4. CONSTRUCTIVE EVICTION: Rule — Landlord's failure to maintain habitable conditions that causes tenant to vacate constitutes constructive eviction. Elements: (1) substantial interference, (2) caused by landlord, (3) tenant vacated within reasonable time. Analysis — Broken heat and toxic mold are substantial. Larry caused it by failing to repair. Tom vacated. Conclusion — Tom likely has a valid constructive eviction defense. Larry cannot collect unpaid rent. Tom may also recover damages for breach of habitability."
    },
    {
        subject: "real-property",
        subjectLabel: "Real Property",
        title: "Easements and Covenants",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "In 1990, Alice granted Bob a written easement to use a path across her land to reach a public road. The easement was recorded. In 2000, Alice sold her land to Carol, who had no actual knowledge of the easement. In 2005, Carol blocked the path. Bob sues Carol to enforce the easement. Carol argues she took the land free of the easement because she had no actual knowledge of it. Discuss whether the easement is enforceable against Carol.",
        issues: "Express easement; easement appurtenant; recording acts; constructive notice; bona fide purchaser; running with the land; dominant and servient tenement.",
        sampleAnswer: "1. VALID EASEMENT: Bob's 1990 easement was written and recorded — a valid express easement appurtenant (benefits Bob's land as dominant tenement, burdens Alice's land as servient tenement). 2. DOES EASEMENT RUN WITH LAND?: An easement appurtenant runs with the land — it binds subsequent owners of the servient tenement. 3. RECORDING ACTS: Rule — A recorded instrument provides constructive notice to all subsequent purchasers. Analysis — The easement was recorded in 1990. Carol, as a subsequent purchaser in 2000, had constructive notice of the recorded easement regardless of actual knowledge. 4. BONA FIDE PURCHASER DEFENSE: Carol cannot claim BFP status against a recorded instrument — she is charged with constructive notice of everything in her chain of title. Conclusion — The easement is fully enforceable against Carol. Recording provided constructive notice. Carol took the land subject to the easement. Bob is entitled to continued use of the path."
    },

    // ===== WILLS, TRUSTS & SUCCESSION =====
    {
        subject: "wills",
        subjectLabel: "Wills, Trusts & Succession",
        title: "Will Execution and Validity",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Helen, age 75, had a will prepared by her attorney. The will was typed and contained the following execution: Helen signed at the bottom in front of her two neighbors, Alice and Bob, who also signed as witnesses. Helen's son Carl was in the room but did not sign. Helen later told her friend she felt pressured by Carl to leave everything to him. After Helen died, Carl contested the will claiming undue influence. Helen's daughter Dana argues the will is valid. Discuss the validity of the will.",
        issues: "Will execution requirements in California; testamentary capacity; undue influence; presence of witnesses; interested witnesses; contest of will.",
        sampleAnswer: "1. FORMAL EXECUTION: California requires (1) writing, (2) signed by testator, (3) witnessed by two persons present at the same time. Analysis — Typed will, Helen signed, two witnesses (Alice and Bob) signed in Helen's presence. Formal execution requirements are met. Carl's presence is irrelevant — he was not required to sign. 2. TESTAMENTARY CAPACITY: Testator must be 18+, of sound mind, understanding nature of will, property, natural objects of bounty, and nature of testamentary act. Analysis — No facts suggest Helen lacked capacity. 3. UNDUE INFLUENCE: Rule — Undue influence requires: (1) susceptible testator, (2) opportunity to influence, (3) disposition to influence for improper purpose, (4) result appearing to be effect of undue influence. Analysis — Helen's age (75) suggests possible susceptibility. Carl was present. Helen felt 'pressured.' However, feeling pressured alone may be insufficient — must show influence overcame her free will. 4. BURDEN OF PROOF: Contestant (Carl, ironically) bears burden of proving undue influence. Conclusion — Will is formally valid. Undue influence claim is weak — Helen's own statement of feeling pressured is relevant but may be insufficient without more evidence that her free will was overcome."
    },
    {
        subject: "wills",
        subjectLabel: "Wills, Trusts & Succession",
        title: "Trust Formation and Modification",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Frank created a revocable living trust in 2015, naming himself as trustee and his daughter Grace as successor trustee and sole beneficiary. In 2020, Frank developed dementia and can no longer manage his affairs. Grace wants to modify the trust to add her own children as beneficiaries. Frank's son Henry, who receives nothing under the trust, objects and seeks to have the trust declared irrevocable and himself named as co-trustee. Discuss the issues.",
        issues: "Revocable vs. irrevocable trusts; settlor's capacity; modification of trusts; successor trustee authority; spendthrift provisions; standing to challenge trust.",
        sampleAnswer: "1. REVOCABLE TRUST AND CAPACITY: A revocable trust can be modified or revoked by the settlor at any time while the settlor has capacity. Frank created a revocable trust. However, Frank now lacks capacity due to dementia — he can no longer exercise his power to modify or revoke. 2. GRACE'S AUTHORITY TO MODIFY: As successor trustee, Grace manages trust assets but her authority is to administer the trust per its terms — NOT to modify beneficial interests for her own children. Modifying to add beneficiaries exceeds trustee authority. This would be a breach of fiduciary duty. 3. HENRY'S STANDING: Henry has no interest under the trust. Generally, only beneficiaries and the settlor have standing to challenge trust administration. Henry's standing is questionable. 4. HENRY AS CO-TRUSTEE: A court may appoint a co-trustee or guardian of the estate to protect Frank's interests if Frank lacks capacity, but Henry has no automatic right to this role. Conclusion — Grace cannot unilaterally modify the trust to add her children. Frank's incapacity freezes the revocable trust in its current form. A court may need to appoint a conservator to protect Frank's interests."
    },
    {
        subject: "wills",
        subjectLabel: "Wills, Trusts & Succession",
        title: "Intestate Succession and Spousal Rights",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Victor died without a will in California. He is survived by his wife Wendy, their two children Ann and Bob, and his mother Mary. Victor owned the following property: (1) A house purchased during the marriage for $600,000; (2) A stock portfolio worth $200,000 inherited from his father during the marriage; (3) A savings account worth $100,000 funded entirely from his salary during the marriage. Discuss how Victor's estate is distributed under California intestate succession law.",
        issues: "California intestate succession; community property vs. separate property; spouse's share; children's share; inherited property as separate property; California Probate Code.",
        sampleAnswer: "1. CHARACTERIZE PROPERTY: (a) House — purchased during marriage with (presumably) community funds = community property; (b) Stock portfolio — inherited during marriage = separate property; (c) Savings account — funded from salary earned during marriage = community property. 2. COMMUNITY PROPERTY INTESTATE SUCCESSION: Rule — Under California Probate Code, a surviving spouse inherits ALL of decedent's share of community property when decedent dies intestate leaving a spouse and children. Analysis — House ($600,000) and savings account ($100,000) are community property. Wendy already owns her half. Victor's half passes entirely to Wendy. Wendy receives 100% of all community property. 3. SEPARATE PROPERTY INTESTATE SUCCESSION: Rule — With spouse and two or more children, separate property is split: 1/3 to spouse, 2/3 to children equally. Analysis — Stock portfolio ($200,000): Wendy gets $66,667; Ann and Bob each get $66,667. 4. MOTHER MARY: Receives nothing — children and spouse take priority. Conclusion — Wendy receives: all community property ($700,000) + 1/3 of separate property ($66,667). Ann and Bob each receive 1/3 of the stock portfolio ($66,667). Mary receives nothing."
    },

    // ===== PROFESSIONAL RESPONSIBILITY =====
    {
        subject: "professional",
        subjectLabel: "Professional Responsibility",
        title: "Confidentiality and the Duty to Disclose",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Attorney Ann represents Carl, who is charged with armed robbery. During a privileged conversation, Carl tells Ann: 'I hid the stolen money under my floorboards and I also plan to lie on the stand and say I was home all night.' Ann knows Carl was not home that night. Discuss Ann's ethical obligations regarding (1) the hidden money and (2) Carl's plan to commit perjury.",
        issues: "Attorney-client privilege; duty of confidentiality; duty of candor to tribunal; client perjury; California Rule 3.3; mandatory vs. permissive disclosure; withdrawal.",
        sampleAnswer: "1. HIDDEN MONEY — CONFIDENTIALITY: Rule — California Rule 1.6 requires attorneys to keep all client information confidential. Exceptions are narrow. Analysis — Carl's disclosure of where he hid money is privileged client communication. Ann may NOT disclose this to authorities. The crime-fraud exception does not apply here — the hiding of money is a past act, not an ongoing or future crime. Conclusion — Ann must keep the location of the money confidential. 2. PLANNED PERJURY — DUTY OF CANDOR: Rule — California Rule 3.3 prohibits an attorney from knowingly offering false evidence or allowing a client to testify falsely. Ann's obligations: (a) Counsel Carl against perjury; (b) If Carl refuses, Ann must consider withdrawal; (c) If Ann cannot withdraw and Carl testifies falsely, Ann may need to take remedial measures including disclosure to the court. Ann cannot simply allow Carl to lie. 3. WITHDRAWAL: If Carl insists on perjury, Ann should seek to withdraw. If withdrawal is denied by the court, Ann faces the difficult position of preventing false testimony while continuing representation. Conclusion — Ann must vigorously try to dissuade Carl from perjury. She cannot present testimony she knows to be false. Withdrawal is likely her best option if Carl insists."
    },
    {
        subject: "professional",
        subjectLabel: "Professional Responsibility",
        title: "Conflicts of Interest and Concurrent Representation",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Attorney Bob simultaneously represents two clients: ABC Corp. in a contract dispute, and XYZ Corp., which is ABC's main competitor, in a trademark matter. The cases are in different courts and involve different legal issues. Bob believes he can competently represent both. Neither client knows about the other. Bob later learns that ABC plans to acquire XYZ, and both clients ask Bob to represent them in the merger negotiations. Discuss the conflict of interest issues.",
        issues: "Concurrent conflicts of interest; California Rule 1.7; duty to disclose; informed consent; direct adversity; material limitation; confidentiality obligations in conflicts.",
        sampleAnswer: "1. INITIAL REPRESENTATION — CONCURRENT CLIENTS: Rule — California Rule 1.7 prohibits concurrent representation if there is a direct conflict or material limitation risk without informed written consent from all affected clients. Analysis — ABC and XYZ are competitors. Even in unrelated matters, representing direct competitors creates a material limitation risk — loyalty to one may affect representation of the other. Bob SHOULD have disclosed this and obtained informed consent before taking both matters. Failure to do so was a rule violation. 2. MERGER REPRESENTATION — DIRECT ADVERSITY: Representing both ABC and XYZ in merger negotiations is a direct conflict — their interests are directly adverse. This conflict is likely NON-CONSENTABLE because Bob cannot provide undivided loyalty to both sides of a negotiation. 3. CONFIDENTIALITY PROBLEM: Bob has confidential information from both clients that is directly relevant to the merger. He cannot use ABC's confidences against ABC for XYZ's benefit, and vice versa. 4. REQUIRED ACTION: Bob must decline the merger representation for both clients. He should consider whether continued representation in the original matters is tenable given the merger situation. Conclusion — Bob has existing and prospective conflict violations. He must withdraw from merger representation and possibly from one or both original matters."
    },
    {
        subject: "professional",
        subjectLabel: "Professional Responsibility",
        title: "Fees, Termination, and Client Files",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Attorney Carol agrees to represent David in a personal injury case on a 40% contingency fee basis. No written fee agreement is signed. Carol works on the case for 6 months and obtains a $100,000 settlement offer. David rejects the offer against Carol's advice and fires Carol. Carol claims she is entitled to 40% of the $100,000 offer ($40,000) as a fee. She also refuses to return David's file until he pays. Discuss the ethical issues.",
        issues: "California contingency fee rules; written fee agreement requirement; quantum meruit; file retention; client's right to terminate; attorney's lien; California Rule 1.5.",
        sampleAnswer: "1. WRITTEN FEE AGREEMENT: Rule — California Rule 1.5 and Business & Professions Code § 6147 require contingency fee agreements to be in writing, signed by the client. Analysis — Carol failed to obtain a written contingency agreement. This violates California law. The contingency agreement may be voidable by David. 2. CAROL'S FEE ENTITLEMENT: Without a valid written contingency agreement, Carol cannot enforce the 40% fee. However, she may recover in quantum meruit — the reasonable value of services actually rendered during the 6 months of work. She cannot demand 40% of a rejected offer. 3. CLIENT'S RIGHT TO TERMINATE: A client may terminate an attorney at any time with or without cause. David properly fired Carol. Termination does not eliminate Carol's right to reasonable compensation for work done. 4. FILE RETENTION: Rule — California Rule 1.16 requires an attorney to promptly return client files upon termination, even if fees are disputed. An attorney cannot hold files hostage for payment — this would harm the client's interests. Carol must return the file immediately. She may pursue fee collection separately. Conclusion — Carol violated the written fee agreement requirement. She is entitled only to quantum meruit. She must immediately return David's file regardless of the fee dispute."
    },

    // ===== COMMUNITY PROPERTY =====
    {
        subject: "community",
        subjectLabel: "Community Property",
        title: "Characterization and Tracing",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Before marriage, Sarah owned a rental property worth $200,000 (her separate property). After marriage, the couple used $100,000 in community funds to renovate the property, increasing its value to $400,000. During the marriage, the property generated $50,000 in rental income. The couple is now divorcing. Discuss how the property and income should be characterized and divided.",
        issues: "Separate vs. community property; commingling; improvements with community funds; Pereira and Van Camp formulas; rental income from separate property; tracing; division at divorce.",
        sampleAnswer: "1. ORIGINAL PROPERTY: The rental property was Sarah's separate property before marriage — remains separate property at its original value. 2. COMMUNITY FUNDS USED FOR RENOVATION: Rule — When community funds improve separate property, the community may acquire an interest (reimbursement right). California Family Code § 2640 gives the community a right to reimbursement for contributions to separate property, without interest, unless the parties agreed otherwise. Analysis — The $100,000 community contribution to renovation is reimbursable to the community at divorce. 3. INCREASED VALUE: The property increased from $200,000 to $400,000. The $100,000 renovation accounts for some increase. Remaining appreciation ($100,000) may be separate property appreciation. 4. RENTAL INCOME: Rule — Income from separate property during marriage is separate property in California (unlike some other community property states). Analysis — The $50,000 rental income is Sarah's separate property, not community property. 5. DIVISION AT DIVORCE: Sarah keeps the property as separate property. Community receives reimbursement of $100,000 renovation contribution (split equally = $50,000 each). Rental income is Sarah's separate property. Conclusion — Sarah retains the property. The community is reimbursed $100,000 for the renovation contribution, divided equally between the parties."
    },
    {
        subject: "community",
        subjectLabel: "Community Property",
        title: "Transmutation and Agreements",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "During their marriage, Mike told his wife Nancy: 'I want you to have my car as your own property.' He handed her the keys but no written document was signed. Mike also used $50,000 of his separate property (an inheritance) to pay down the mortgage on their community property home. The couple is now divorcing. Mike wants the car back and claims a $50,000 reimbursement for the mortgage payment. Discuss the transmutation and reimbursement issues.",
        issues: "Transmutation requirements in California; California Family Code 852; written express declaration requirement; separate property contributions to community property; Family Code 2640 reimbursement.",
        sampleAnswer: "1. TRANSMUTATION OF CAR: Rule — California Family Code § 852 requires that any transmutation of property (changing its character from separate to community or vice versa) must be made in writing by an express declaration. An oral statement or gesture is insufficient. Analysis — Mike's oral statement and handing over keys does NOT constitute a valid transmutation under California law. No written express declaration was made. Conclusion — The car remains Mike's separate property. Nancy does not own it. Mike can reclaim it. 2. SEPARATE PROPERTY CONTRIBUTION TO COMMUNITY MORTGAGE: Rule — California Family Code § 2640 provides that a spouse who contributes separate property funds to the acquisition or improvement of community property is entitled to reimbursement of that contribution at divorce, without interest, unless waived in writing. Analysis — Mike used $50,000 separate property inheritance to pay down the community property mortgage. This was a contribution to community property acquisition. Conclusion — Mike is entitled to reimbursement of $50,000 from the community property before the remaining equity is divided equally. The reimbursement comes off the top before the 50/50 split."
    },
    {
        subject: "community",
        subjectLabel: "Community Property",
        title: "Division at Divorce and Debts",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Tom and Sue are divorcing after 15 years of marriage. Tom has a pension that he began contributing to 5 years before marriage and continued during the 15-year marriage. The pension is currently worth $600,000. Tom also has $30,000 in credit card debt he ran up buying gambling equipment for personal use during the marriage. Sue has $20,000 in student loan debt she incurred before marriage. Discuss how the pension, Tom's credit card debt, and Sue's student loan debt should be treated at divorce.",
        issues: "Division of pension at divorce; time rule for apportioning separate and community interest in pension; community debt; separate debt; California equal division rule; Family Code 2550.",
        sampleAnswer: "1. PENSION APPORTIONMENT: Rule — A pension earned partly before and partly during marriage is apportioned using the 'time rule': the community interest = (years of marriage during pension service / total years of pension service) × pension value. Analysis — Tom worked 5 years before marriage + 15 years during marriage = 20 total years. Community fraction = 15/20 = 75%. Community interest = $600,000 × 75% = $450,000 (divided equally = $225,000 each). Tom's separate interest = $600,000 × 25% = $150,000 (Tom's alone). 2. TOM'S CREDIT CARD DEBT: Rule — Debts incurred during marriage for community purposes are community debts. Debts for personal/separate purposes may be characterized differently. Analysis — Gambling equipment for personal use may be Tom's separate debt, or if the gambling was a family activity, community debt. Most likely characterized as Tom's debt given personal nature. If community debt, both are equally liable. 3. SUE'S STUDENT LOAN DEBT: Rule — Debts incurred before marriage are separate debts of the incurring spouse. Analysis — Sue's pre-marriage student loans are her separate debt. Tom is not liable. Conclusion — Pension divided 75% community/25% separate. Tom's gambling debt likely his alone. Sue's student loans are her separate debt."
    },

    // ===== REMEDIES =====
    {
        subject: "remedies",
        subjectLabel: "Remedies",
        title: "Compensatory Damages and Mitigation",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "ABC Co. contracts with Builder to construct a warehouse for $500,000 by December 1. Builder abandons the project when it is 60% complete, having been paid $300,000 already. ABC hires a second contractor to finish the work for $280,000. ABC also lost a $50,000 lease deal because the warehouse was not ready on time. Builder claims ABC should have found a cheaper contractor and that the lost lease deal was unforeseeable. Discuss ABC's damages.",
        issues: "Expectation damages; cost of completion; consequential damages; Hadley v. Baxendale foreseeability; mitigation of damages; benefit of the bargain.",
        sampleAnswer: "1. EXPECTATION DAMAGES — COST OF COMPLETION: Rule — The non-breaching party is entitled to benefit of the bargain. For construction contracts, this is typically the cost to complete minus any unpaid contract price. Analysis — ABC paid $300,000 and got a 60% complete warehouse. Remaining contract value = $200,000. ABC paid $280,000 to complete — $80,000 MORE than the remaining contract price. Direct damages = $80,000. 2. MITIGATION: Rule — Non-breaching party must take reasonable steps to mitigate damages. Analysis — ABC hired a second contractor. Builder argues ABC should have found cheaper completion. But the duty to mitigate requires only reasonable efforts — ABC need not accept an inferior contractor or sacrifice quality. If $280,000 was a reasonable market rate, ABC satisfied its mitigation duty. 3. CONSEQUENTIAL DAMAGES — LOST LEASE: Rule — Under Hadley v. Baxendale, consequential damages are recoverable only if they were foreseeable at the time of contracting. Analysis — A lost lease deal from late completion is a foreseeable consequence of a construction contractor's breach — delays in construction commonly cause downstream business losses. Conclusion — ABC recovers: $80,000 direct damages (cost overrun) + $50,000 consequential damages (lost lease, if foreseeable) = $130,000 total, assuming mitigation was reasonable."
    },
    {
        subject: "remedies",
        subjectLabel: "Remedies",
        title: "Equitable Remedies and Injunctions",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "MegaCorp plans to demolish a historic 100-year-old building tomorrow morning to build a parking lot. A neighborhood preservation group seeks a temporary restraining order (TRO) and preliminary injunction to stop the demolition. MegaCorp argues it has a legal right to demolish its own property and that any delay costs $10,000 per day. Discuss whether the court should grant the TRO and preliminary injunction.",
        issues: "Temporary restraining order requirements; preliminary injunction standard; likelihood of success on merits; irreparable harm; balance of hardships; public interest; Winter v. Natural Resources Defense Council.",
        sampleAnswer: "1. TRO STANDARD: A court may grant a TRO without notice if: (1) immediate irreparable injury will occur before the adverse party can be heard, and (2) applicant's attorney certifies efforts to notify. Analysis — Demolition tomorrow creates urgency. TRO is appropriate to preserve status quo pending hearing. 2. PRELIMINARY INJUNCTION — FOUR FACTORS (Winter standard): (1) LIKELIHOOD OF SUCCESS ON MERITS: Preservation group must show a likely legal basis to stop demolition (e.g., historic preservation law, environmental regulations, zoning violations). Depends on applicable law. (2) IRREPARABLE HARM: Once demolished, the 100-year-old building cannot be restored — money damages are inadequate. Strong showing of irreparable harm. (3) BALANCE OF HARDSHIPS: MegaCorp loses $10,000/day. Preservation group loses an irreplaceable historic structure. Balance favors preservation — financial harm is quantifiable and compensable; destruction of historic building is not. (4) PUBLIC INTEREST: Preservation of historic buildings often serves strong public interest. Favors injunction. 3. BOND REQUIREMENT: Court will likely require preservation group to post a bond to cover MegaCorp's daily losses if injunction ultimately fails. Conclusion — Court should grant TRO immediately and likely grant preliminary injunction. Irreparable harm and public interest factors are compelling. Financial harm to MegaCorp can be addressed through bond."
    },
    {
        subject: "remedies",
        subjectLabel: "Remedies",
        title: "Restitution and Unjust Enrichment",
        instructions: "Read the fact pattern carefully. Identify all legal issues, state the applicable rules, apply the rules to the facts, and reach a conclusion for each issue. Write in IRAC format.",
        prompt: "Pete, a licensed contractor, enters into an oral contract with Helen to renovate her kitchen for $40,000. Under the Statute of Frauds, the contract is unenforceable because it was not in writing and cannot be performed within one year. Pete completes the renovation. Helen refuses to pay anything, arguing the contract is unenforceable. Pete sues. Discuss Pete's available remedies.",
        issues: "Statute of Frauds unenforceability; quasi-contract; unjust enrichment; quantum meruit; restitution; off the contract remedies; reasonable value of services.",
        sampleAnswer: "1. CONTRACT CLAIM FAILS: The oral contract is unenforceable under the Statute of Frauds. Pete cannot sue on the contract itself for $40,000. 2. UNJUST ENRICHMENT / QUASI-CONTRACT: Rule — Even when a contract is unenforceable, a party who confers a benefit on another may recover in quasi-contract (implied-in-law contract) to prevent unjust enrichment. Elements: (1) plaintiff conferred a benefit on defendant, (2) defendant had knowledge of the benefit, (3) defendant accepted and retained the benefit, (4) it would be unjust to allow retention without payment. Analysis — Pete completed the renovation (benefit conferred). Helen accepted the finished kitchen (retention). Helen pays nothing while enjoying an improved kitchen — classic unjust enrichment. 3. QUANTUM MERUIT: Pete may recover the reasonable value of his services (quantum meruit) — not necessarily the contract price, but the fair market value of the renovation work. This may be more or less than the $40,000 agreed price. 4. HELEN'S DEFENSE: Helen cannot use the Statute of Frauds as a shield to receive free renovation work. Equity will not allow unjust enrichment even when the underlying contract is unenforceable. Conclusion — Pete cannot enforce the contract but is entitled to recover the reasonable value of his services in quasi-contract/quantum meruit. The Statute of Frauds bars the contract claim but not the restitution claim."
    }

];
